"""Added lat and long to county

Revision ID: 522221935b00
Revises: 016adf2285e5
Create Date: 2025-04-24 12:58:26.861445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522221935b00'
down_revision = '016adf2285e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('county', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('county', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    # ### end Alembic commands ###
